name: Hello World

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - name: Echo Hello World
        run: echo "Hello World"
      - run: uptime
