name: Hello World
on: workflow_dispatch
jobs:
  container_action:
    runs-on: self-hosted
    steps:
      - name: Run Checkov action
        id: checkov
        uses: docker://ghcr.io/bridgecrewio/checkov:3.2.477@sha256:51bebaca76536e985118a6af41ff4811a1b909a5e370492a955b4b6c82da6a88
        with:
          entrypoint: /entrypoint.sh
          directory: terraform/
          quiet: true # Only failed checks
          soft_fail: true # Do not return an error code if there are failed checks
          framework: terraform # Only terraform checks
          external_checks_dirs: images/atlantis/checkov_policies/ # Contains custom checks
          # - `CKV_GCP_custom_1` Disallow sensitive data sources to be used as an input in other data blocks.
          container_user: 1000 # Run container as user with uid
  hello:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Echo Hello World
        run: echo "Hello World"
      - run: uptime
