name: Hello World

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - run: sleep 30
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Echo Hello World
        run: echo "Hello World"
      - run: uptime
